name             'vlg-graphite'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-graphite'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.51'
depends		 'vlg-base'
depends		 'vlg-java'
depends		 'vlg-diamond'
depends          'vlg-s3cmd'
