name             'vlg-aws-developer-tools'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-aws-developer-tools'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends		 'vlg-base'
depends		 'vlg-java'
depends		 'aws_developer_tools'
