name             'vlg-base'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-base'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.156'
depends		 'now'
depends		 'chef-solo-search'
depends		 'chef-client'
depends		 'vlg-ephemeral'
depends		 'hostsfile'
depends		 'selinux'
depends		 'iptables'
depends		 'yum'
depends		 'yum-epel'
depends		 'build-essential'
depends		 'packages'
depends		 'sshd'
depends		 'users'
depends		 'sudo'
depends		 'sysctl'
depends		 'nrpe'
depends		 'limits'
depends		 'ntp'
depends		 'vlg-dotfiles'
depends		 'vlg-cron'
depends		 'vlg-swap'
depends		 'rsyslog'
depends		 'aws'
depends		 'resolver'
depends		 'dynect'
depends		 'python'
depends		 'hipchat'
depends		 'vlg-diamond'
