name             'vlg-opt-mq'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-opt-mq'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.18'
depends          'vlg-base'
depends		 'vlg-activemq'
depends          'vlg-opt-common'
