name             'vlg-rundeck'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-rundeck'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.46'
depends		 'vlg-base'
depends		 'vlg-haproxy'
depends		 'vlg-java'
depends		 'vlg-ssh-key'
depends		 'vlg-s3cmd'
depends    	 'mysql'
depends		 'vlg-parallel'
depends		 'vlg-groovy'
depends		 'vlg-deploy'
depends      'perl'
