name             'vlg-opt-ns'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-opt-ns'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.2'
depends          'vlg-base'
depends		 'vlg-clicksense'
depends		 'vlg-tomcat'
depends          'vlg-opt-common'
