name             'vlg-activemq'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-activemq'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.11'
depends          'vlg-base'
depends          'ark'
depends          'vlg-java'
