Vagrant.configure(2) do |config|
	config.vm.network :public_network, :bridge => $network_interface
	  config.vm.define "test" do |test|
		test.vm.box = "centos"
		test.vm.network "forwarded_port", guest: 80, host: 8080
		config.vm.network :forwarded_port, guest: 3306, host: 3306
		config.vm.network :forwarded_port, guest: 7990, host: 7990
		config.vm.network :forwarded_port, guest: 8443, host: 8443


		test.vm.provision "chef_solo" do |chef|
		  chef.cookbooks_path = "../../cookbooks/"
		  chef.environments_path = "../../environments/"
		  chef.environment = "development"
		  chef.roles_path = "../../roles/"
		  chef.data_bags_path = "../../data_bags/"
		  chef.node_name = "stash"
		  chef.add_recipe  "stash"
		end
	end
	  
end