name             'vlg-solr'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-solr'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.16'
depends		 'vlg-base'
depends		 'vlg-java'
depends		 'ark'
