name             'vlg-lu-db'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-lu-db'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.17'
depends          'vlg-base'
depends		 'vlg-s3cmd'
depends          'vlg-diamond'
depends		 'mysql'
