name             'vlg-log'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-log'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
depends	 	 'vlg-base'
depends		 'vlg-s3cmd'
depends		 'vlg-s3fs'
