name             'vlg-lz-sm'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-lz-sm'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.29'
depends          'vlg-base'
depends          'vlg-java'
depends          'vlg-storm'
depends          'vlg-clicksense'
