name             'vlg-data-ftp'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-data-ftp'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.16'
depends		 'onddo_proftpd'
depends		 'vlg-ssl'
depends		 'vlg-s3cmd'
