name             'vlg-opt-lite-mp'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-opt-lite-mp'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.10'
depends          'vlg-base'
depends		 'vlg-clicksense'
depends		 'vlg-tomcat'
depends          'vlg-opt-common'
