name             'vlg-all-in-one'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-all-in-one'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.3'
depends		 'vlg-base'
depends		 'vlg-java'
depends    'vlg-clicksense'
depends    'maven'
depends		 'redisio'
depends		 'mysql'
depends		 'vlg-activemq'
depends		 'memcached'
depends		 'vlg-gams'
depends		 'couchbase'
depends		 'vlg-storm'
depends		 'vlg-zookeeper'
depends		 'vlg-kafka'
depends		 'vlg-solr'