name             'vlg-lz-pi'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-lz-pi'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.1'
depends		 'vlg-base'
depends		 'vlg-haproxy'
depends		 'vlg-ssl'