name             'vlg-lu-mc'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-lu-mc'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.4'
depends          'vlg-base'
depends		 'vlg-clicksense'
depends          'vlg-diamond'
