export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/graphite/bin
export PYTHONPATH=/usr/local/graphite/lib/python2.6/site-packages
Color_Off='\e[0m'
Red='\e[0;31m'
Yellow='\e[0;33m'
Cyan='\e[0;36m'
FANCY="\342\207\222"
export PS1="\[$Cyan\]\h: \[$Red\]\w \[$Yellow\]$FANCY \[$Color_Off\] "
export EDITOR=vim
alias df='df -h'
alias cd..='cd ..'
alias ls='ls -F --color'
alias ..='cd ..'
alias srd='screen -rd'
alias grep='grep --color'
alias ducks='sudo du -cks * 2> /dev/null | sort -rn | head -11'
alias nagios='ssh -i .ssh/gio-keypair.pem ec2-user@nagios'
alias cs.tail='tail -f /home/vlg/ClickSense/local/logs/application.log /home/vlg/ClickSense/local/logs/adserver.log /home/vlg/tomcat/logs/catalina.out'
alias status.ready='curl http://localhost:8080/status/ready -w "\n"'
alias status.ready.loop='while true; do timeout 1 curl http://localhost:8080/status/ready -w "\n"; sleep 1; done'
alias adserver.log='tail -100f /home/vlg/ClickSense/local/logs/adserver.log'
alias application.log='tail -100f /home/vlg/ClickSense/local/logs/application.log'
alias catalina.out='tail -100f /home/vlg/tomcat/logs/catalina.out'
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export LC_MONETARY=LANG=en_US.UTF-8
export HISTFILESIZE=
export HISTSIZE=
export LC_ALL=$LANG
