name             'vlg-lu-cm'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-lu-cm'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.32'
depends          'vlg-base'
depends		 'vlg-clicksense'
depends		 'vlg-diamond'
depends		 'vlg-tomcat'
