name             'vlg-lz-sl'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-lz-sl'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.20'
depends          'vlg-base'
depends		 'vlg-solr'
depends		 'vlg-ssl'
depends          'vlg-zookeeper'
