name             'vlg-lu-px'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-lu-px'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.102'
depends		 'vlg-base'
depends		 'vlg-ssl'
depends          'vlg-diamond'
depends		 'vlg-haproxy'
