name             'vlg-lz-cu'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-lz-cu'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'vlg-base'
depends          'vlg-tomcat'
depends          'vlg-s3cmd'