name             'vlg-deploy'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-deploy'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.17'
depends		 'vlg-base'
depends		 'vlg-ssh-key'
depends		 'vlg-java'
