name             'vlg-lz-da'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-lz-da'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.20'
depends          'vlg-base'
depends          'vlg-tomcat'
depends          'vlg-s3cmd'
