name             'vlg-rnd-tv'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-rnd-tv'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.2'
depends		 'vlg-base'
depends          'vlg-anaconda'
depends          'vlg-java'
depends          'scala'
depends		 'vlg-s3cmd'
