name             'vlg-opt-lite-px'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-opt-lite-px'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.6'
depends		 'vlg-base'
depends		 'vlg-haproxy'
depends          'vlg-opt-common'
