name             'vlg-data-cdh'
maintainer       'Videology Group, Inc.'
maintainer_email 'gio@videologygroup.com'
license          'All rights reserved'
description      'Installs/Configures vlg-data-cdh'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.60'
depends          'vlg-base'
depends		 'vlg-java'
depends		 'vlg-ssh-key'
depends		 'vlg-diamond'
